// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYANjxhokj3LbqmXAftKNQjeIjpx2ZBp0',
    appId: '1:502522474758:web:20a46d5318502476362e87',
    messagingSenderId: '502522474758',
    projectId: 'loginsignup-bf06b',
    authDomain: 'loginsignup-bf06b.firebaseapp.com',
    storageBucket: 'loginsignup-bf06b.appspot.com',
    measurementId: 'G-3C96MZ85TV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDt4YmBrhZDTQMg8eOg6m_yvqFC8VClTrM',
    appId: '1:502522474758:android:2f47abcd85e0c122362e87',
    messagingSenderId: '502522474758',
    projectId: 'loginsignup-bf06b',
    storageBucket: 'loginsignup-bf06b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCd7azlHwR_xfPnq1CxCiyx8tUsjfvEEU8',
    appId: '1:502522474758:ios:cff1ca7d0dee7254362e87',
    messagingSenderId: '502522474758',
    projectId: 'loginsignup-bf06b',
    storageBucket: 'loginsignup-bf06b.appspot.com',
    iosBundleId: 'com.example.loginsignup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCd7azlHwR_xfPnq1CxCiyx8tUsjfvEEU8',
    appId: '1:502522474758:ios:cff1ca7d0dee7254362e87',
    messagingSenderId: '502522474758',
    projectId: 'loginsignup-bf06b',
    storageBucket: 'loginsignup-bf06b.appspot.com',
    iosBundleId: 'com.example.loginsignup',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYANjxhokj3LbqmXAftKNQjeIjpx2ZBp0',
    appId: '1:502522474758:web:62e7f141d05b1821362e87',
    messagingSenderId: '502522474758',
    projectId: 'loginsignup-bf06b',
    authDomain: 'loginsignup-bf06b.firebaseapp.com',
    storageBucket: 'loginsignup-bf06b.appspot.com',
    measurementId: 'G-J3091RFJ6Y',
  );

}